<?php 


if (function_exists('acf_add_local_field_group')) {

    acf_add_local_field_group(array(
    'key' => 'group_69424998c467b',
    'title' => __('Table of Contents Settings', 'modularity-toc'),
    'fields' => array(
        0 => array(
            'key' => 'field_6942499969780',
            'label' => __('Include headings from following sidebars', 'modularity-toc'),
            'name' => 'sidebars',
            'aria-label' => '',
            'type' => 'select',
            'instructions' => __('Headings in main container will always be included', 'modularity-toc'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
            ),
            'default_value' => array(
            ),
            'return_format' => 'value',
            'multiple' => 1,
            'allow_custom' => 0,
            'placeholder' => '',
            'allow_null' => 0,
            'allow_in_bindings' => 0,
            'ui' => 1,
            'ajax' => 0,
            'create_options' => 0,
            'save_options' => 0,
            'search_placeholder' => '',
        ),
        1 => array(
            'key' => 'field_694249ea69781',
            'label' => __('Which heading levels to include in list', 'modularity-toc'),
            'name' => 'heading_levels',
            'aria-label' => '',
            'type' => 'select',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'h2' => __('H2', 'modularity-toc'),
                'h3' => __('H3', 'modularity-toc'),
                'h4' => __('H4', 'modularity-toc'),
            ),
            'default_value' => array(
                0 => 'h2',
            ),
            'return_format' => 'value',
            'multiple' => 1,
            'allow_custom' => 0,
            'placeholder' => '',
            'allow_null' => 0,
            'allow_in_bindings' => 0,
            'ui' => 1,
            'ajax' => 0,
            'create_options' => 0,
            'save_options' => 0,
            'search_placeholder' => '',
        ),
        2 => array(
            'key' => 'field_6942556c3aa83',
            'label' => __('Place in card?', 'modularity-toc'),
            'name' => 'place_in_card',
            'aria-label' => '',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => __('Yes', 'modularity-toc'),
            'default_value' => 0,
            'allow_in_bindings' => 0,
            'ui' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
        3 => array(
            'key' => 'field_694255833aa84',
            'label' => __('Ignore all headings in card except for card header?', 'modularity-toc'),
            'name' => 'ignore_card_sub_headers',
            'aria-label' => '',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => __('Yes', 'modularity-toc'),
            'default_value' => 0,
            'allow_in_bindings' => 0,
            'ui' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
        4 => array(
            'key' => 'field_67d6a94cb3c02',
            'label' => __('Hide on mobile?', 'modularity-toc'),
            'name' => 'hide_on_mobile',
            'aria-label' => '',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => __('Yes', 'modularity-toc'),
            'default_value' => 0,
            'allow_in_bindings' => 0,
            'ui' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
        5 => array(
            'key' => 'field_67d6c68ab3c03',
            'label' => __('Hide on desktop?', 'modularity-toc'),
            'name' => 'hide_on_desktop',
            'aria-label' => '',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => __('Yes', 'modularity-toc'),
            'default_value' => 0,
            'allow_in_bindings' => 0,
            'ui' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
        6 => array(
            'key' => 'field_67d8328fb3c04',
            'label' => '',
            'name' => 'settings_version',
            'aria-label' => '',
            'type' => 'hidden',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '2',
            'allow_in_bindings' => 0,
        ),
    ),
    'location' => array(
        0 => array(
            0 => array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'mod-toc',
            ),
        ),
        1 => array(
            0 => array(
                'param' => 'block',
                'operator' => '==',
                'value' => 'acf/toc',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'left',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
    'display_title' => '',
    'acfe_autosync' => array(
        0 => 'json',
    ),
    'acfe_form' => 0,
    'acfe_meta' => '',
    'acfe_note' => '',
));

}
